In [18]:
#Objective: The objective of this assignment is to gain practical experience with fundamental operations
#in TensorFlow, including creating and manipulating matrices, performing arithmetic operations on
#tensors, and understanding the difference between TensorFlow constants and variables.
#Part 1: Theoretical Questionk
#Tc What are the different data structures used in Tensorflow?. Give some examplesc
#Cc How does the TensorFlow constant differ from a TensorFlow variable? Explain with an examplec
#=c Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.

In [20]:
import tensorflow as tf

# Creating a 2D tensor (matrix)
matrix = tf.constant([[1, 2], [3, 4]])
print(matrix)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [22]:
# Creating a variable
variable = tf.Variable([[1, 2], [3, 4]])
variable.assign([[5, 6], [7, 8]])  # Updating the variable
print(variable)


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>


In [24]:
# Creating a constant
constant = tf.constant([[1, 2], [3, 4]])
# constant[0, 0] = 5  # This would raise an error!
print(constant)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [26]:
# Creating a variable
variable = tf.Variable([[1, 2], [3, 4]])
variable.assign([[5, 6], [7, 8]])  # Changing the variable's value
print(variable)


<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]])>


In [28]:
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])
result_add = tf.add(matrix_a, matrix_b)
print(result_add)  # Output: [[ 6  8]
                   #          [10 12]]


tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [30]:
result_mul = tf.matmul(matrix_a, matrix_b)
print(result_mul)  # Output: [[19 22]
                   #          [43 50]]


tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [32]:
result_elem_mul = tf.multiply(matrix_a, matrix_b)
print(result_elem_mul)  # Output: [[ 5 12]
                         #          [21 32]]


tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)


In [35]:
#Part 2: Practical Implementation
#Task 1: Creating and Manipulating MatricekTc Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display thevalues of matrix AcCc Create a Gaussian matrix B with dimensions 4x4, using TensorFlow's truncated_normal function. Displaythe values of matrix Bc=c Create a matrix C with dimensions 2x2, where the values are drawn from a normal distribution with amean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the valuesof matrix Cc~c Perform matrix addition between matrix A and matrix B, and store the result in matrix Dcwc Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.




import tensorflow as tf

# Create a normal matrix A with dimensions 3x3
A = tf.random.normal(shape=(3, 3))
print("Matrix A:\n", A.numpy())


Matrix A:
 [[ 1.4705269   1.4338667   0.78456014]
 [-2.9998248  -1.2183839   1.6814219 ]
 [-0.2474151   0.9180344   1.4883523 ]]


In [37]:
# Create a Gaussian matrix B with dimensions 4x4
B = tf.random.truncated_normal(shape=(4, 4))
print("Matrix B:\n", B.numpy())


Matrix B:
 [[ 0.35872424  0.9240697   0.31481153  0.29109308]
 [ 0.88402385 -0.9306751  -0.49960476  0.98910856]
 [-0.44603264  1.3499297  -0.04984836 -0.48478368]
 [-0.8730984   0.8997157   0.548015    0.8685129 ]]


In [39]:
# Create a matrix C with dimensions 2x2
C = tf.random.normal(shape=(2, 2), mean=3.0, stddev=0.5)
print("Matrix C:\n", C.numpy())

# Perform matrix addition between A and B (ensure A and B are compatible)
D = tf.add(A[:4, :4], B)  # Adjusting A to be 4x4 for addition
print("Matrix D (A + B):\n", D.numpy())

# Perform matrix multiplication between C and D
E = tf.matmul(C, D)
print("Matrix E (C * D):\n", E.numpy())


Matrix C:
 [[2.6094916 2.9237618]
 [2.5550604 1.9552151]]


InvalidArgumentError: {{function_node __wrapped__AddV2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Incompatible shapes: [3,3] vs. [4,4] [Op:AddV2] name: 